workflows:
  android_caregiver_aab:
    name: caregiver-android-aab
    max_build_duration: 120
    environment:
      node: 20.19.4
      java: 17
      android_signing:
        - dongdong-upload
      groups:
        - google_credentials
      vars:
        APP_DIR: .
        NODE_ENV: "production"
        # Versioning (prevent Play upload failures due to non-increasing versionCode)
        # - Always publish with a high, monotonic versionCode derived from CM_BUILD_NUMBER.
        # - Safe even if you previously uploaded smaller versionCodes (e.g. 1~100).
        VC_BASE: 100000
        # Public app config (keep builds deterministic even if Codemagic UI vars are missing)
        EXPO_PUBLIC_API_URL: "http://api.dongdong.io:3000/api/v1"
        EXPO_PUBLIC_KAKAO_APP_KEY: "6800df07055f12ec3dd904c9db31e1dd"
        KAKAO_APP_KEY: "6800df07055f12ec3dd904c9db31e1dd"
        # Secrets must be set in Codemagic UI (Environment variables / Groups):
        # - CM_KEYSTORE_PASSWORD
        # - CM_KEY_PASSWORD   (if different from store password)
        # Secure file upload (keystore): upload as `upload.jks` (or change KEYSTORE_FILE below).
        KEYSTORE_FILE: upload.jks
    scripts:
      - name: Install dependencies (yarn)
        script: |
          cd "$APP_DIR"
          echo "=== CI_SOURCE ==="
          git rev-parse HEAD 2>/dev/null || true
          git remote -v 2>/dev/null || true
          echo "============="
          # Yarn install (deterministic, avoid global binary collisions on Codemagic images)
          if command -v corepack >/dev/null 2>&1; then
            corepack enable
            corepack prepare yarn@1.22.22 --activate
          else
            npm i -g yarn@1.22.22 --force
          fi
          yarn --version
          # IMPORTANT:
          # NODE_ENV is set to "production" for Expo config stability, but we still need devDependencies
          # (e.g. react-native-svg-transformer used by metro.config.js).
          export YARN_PRODUCTION=false
          yarn install --frozen-lockfile --ignore-engines --production=false
          node -e "require('./metro.config.js'); console.log('[ci] metro.config.js OK')" || exit 2
      - name: Set Android versionCode (CI monotonic)
        script: |
          cd "$APP_DIR"
          node -e "
            const fs=require('fs');
            const p='./app.json';
            const j=JSON.parse(fs.readFileSync(p,'utf8'));
            const base=Number(process.env.VC_BASE||100000);
            const n=Number(process.env.CM_BUILD_NUMBER||0);
            const vc=base + (Number.isFinite(n)&&n>0?n:1);
            j.expo=j.expo||{};
            j.expo.android=j.expo.android||{};
            j.expo.android.versionCode=vc;
            fs.writeFileSync(p, JSON.stringify(j,null,2)+'\\n');
            console.log('[ci] android.versionCode='+vc);
          "
      - name: Expo prebuild (android)
        script: |
          cd "$APP_DIR"
          rm -rf android ios
          npx expo prebuild --platform android --clean
      - name: Android bundleRelease (AAB)
        script: |
          cd "$APP_DIR/android"
          # Resolve keystore file path robustly (Codemagic can expose it via different mechanisms).
          KEYSTORE_PATH=""
          echo "KEYSTORE_FILE=${KEYSTORE_FILE:-}"
          echo "CM_KEYSTORE_PATH=${CM_KEYSTORE_PATH:-}"
          echo "CM_SECURE_FILES_PATH=${CM_SECURE_FILES_PATH:-}"
          echo "CM_BUILD_DIR=${CM_BUILD_DIR:-}"

          # 1) Codemagic Android keystore integration (preferred)
          if [ -n "${CM_KEYSTORE_PATH:-}" ] && [ -f "${CM_KEYSTORE_PATH:-}" ]; then
            KEYSTORE_PATH="${CM_KEYSTORE_PATH:-}"
          fi
          # Some setups expose CM_KEYSTORE_PATH as a directory. If so, list it and locate a .jks inside.
          if [ -z "$KEYSTORE_PATH" ] && [ -n "${CM_KEYSTORE_PATH:-}" ] && [ -d "${CM_KEYSTORE_PATH:-}" ]; then
            echo "CM_KEYSTORE_PATH is a directory; listing:"
            ls -la "${CM_KEYSTORE_PATH:-}" || true
            # Prefer the expected KEYSTORE_FILE name if present, otherwise pick the first *.jks.
            if [ -n "${KEYSTORE_FILE:-}" ] && [ -f "${CM_KEYSTORE_PATH:-}/$KEYSTORE_FILE" ]; then
              KEYSTORE_PATH="${CM_KEYSTORE_PATH:-}/$KEYSTORE_FILE"
            else
              KEYSTORE_PATH="$(find "${CM_KEYSTORE_PATH:-}" -maxdepth 2 -type f -name '*.jks' 2>/dev/null | head -n 1 || true)"
            fi
          fi

          # 2) Secure files
          if [ -z "$KEYSTORE_PATH" ] && [ -n "${CM_SECURE_FILES_PATH:-}" ] && [ -f "${CM_SECURE_FILES_PATH:-}/$KEYSTORE_FILE" ]; then
            KEYSTORE_PATH="${CM_SECURE_FILES_PATH:-}/$KEYSTORE_FILE"
          fi

          # 3) Build dir (if user uploaded as a generic file)
          if [ -z "$KEYSTORE_PATH" ] && [ -f "$CM_BUILD_DIR/$KEYSTORE_FILE" ]; then
            KEYSTORE_PATH="$CM_BUILD_DIR/$KEYSTORE_FILE"
          fi

          # 4) Fallback: find any .jks under secure files / home
          if [ -z "$KEYSTORE_PATH" ] && [ -n "${CM_SECURE_FILES_PATH:-}" ] && [ -d "${CM_SECURE_FILES_PATH:-}" ]; then
            KEYSTORE_PATH="$(find "$CM_SECURE_FILES_PATH" -maxdepth 2 -type f -name '*.jks' 2>/dev/null | head -n 1 || true)"
          fi
          if [ -z "$KEYSTORE_PATH" ]; then
            KEYSTORE_PATH="$(find "$HOME" -maxdepth 5 -type f -name '*.jks' 2>/dev/null | head -n 1 || true)"
          fi

          if [ -z "$KEYSTORE_PATH" ] || [ ! -f "$KEYSTORE_PATH" ]; then
            echo "Keystore file not found. Upload a .jks (Android keystore integration or Secure files) and ensure CM_KEYSTORE_PASSWORD is set."
            exit 2
          fi
          echo "KEYSTORE_PATH=$KEYSTORE_PATH"
          ls -la "$KEYSTORE_PATH" || true
          file "$KEYSTORE_PATH" 2>/dev/null || true

          # Auto-detect alias to avoid manual mistakes (works when keystore has a single entry).
          KEY_ALIAS="${CM_KEY_ALIAS:-}"
          if [ -z "$KEY_ALIAS" ]; then
            KEY_ALIAS="$(keytool -list -keystore "$KEYSTORE_PATH" -storepass "$CM_KEYSTORE_PASSWORD" 2>/dev/null | awk -F, 'NF>=1 {gsub(/^[ \t]+|[ \t]+$/, "", $1); if ($1!="") {print $1; exit}}')"
          fi
          if [ -z "$KEY_ALIAS" ]; then
            echo "Failed to detect key alias. Set CM_KEY_ALIAS explicitly."
            exit 2
          fi

          KEY_PASS="${CM_KEY_PASSWORD:-$CM_KEYSTORE_PASSWORD}"

          echo "=== SIGNING_INFO (caregiver) ==="
          echo "package=$(node -e \"console.log(require('../app.json').expo.android.package)\")"
          echo "versionCode=$(node -e \"console.log(require('../app.json').expo.android.versionCode)\")"
          echo "KEY_ALIAS=$KEY_ALIAS"
          keytool -list -v -keystore "$KEYSTORE_PATH" -storepass "$CM_KEYSTORE_PASSWORD" -alias "$KEY_ALIAS" 2>/dev/null | grep -E "SHA1:|SHA256:" || true
          if command -v openssl >/dev/null 2>&1; then
            KEY_HASH="$(keytool -exportcert -alias "$KEY_ALIAS" -keystore "$KEYSTORE_PATH" -storepass "$CM_KEYSTORE_PASSWORD" 2>/dev/null | openssl sha1 -binary | openssl base64 2>/dev/null || true)"
            if [ -n "$KEY_HASH" ]; then
              echo "KAKAO_KEY_HASH=$KEY_HASH"
              echo "$KEY_HASH" > "$CM_BUILD_DIR/kakao_key_hash.txt"
            fi
          fi

          ./gradlew --no-daemon --max-workers=1 :app:bundleRelease \
            -Pandroid.injected.signing.store.file="$KEYSTORE_PATH" \
            -Pandroid.injected.signing.store.password="$CM_KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$KEY_PASS"
      - name: Verify + SHA256
        script: |
          cd "$APP_DIR/android"
          AAB="$(ls -1 app/build/outputs/bundle/release/*.aab | head -n 1 || true)"
          if [ -z "$AAB" ]; then
            echo "AAB not found"
            exit 3
          fi
          echo "AAB=$AAB"
          jarsigner -verify -verbose -certs "$AAB" || exit 4
          sha256sum "$AAB" | tee "$AAB.sha256.txt"
    artifacts:
      - kakao_key_hash.txt
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/bundle/release/*.sha256.txt
      - android/app/build/outputs/mapping/release/mapping.txt
      - android/app/build/reports/**/*
    publishing:
      google_play:
        # Contents of the JSON key file for Google Play service account saved
        # as a secret environment variable (recommended name):
        #   GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        # Internal testing track
        track: internal
        # Play Console can require draft releases while the app is still in "draft" state.
        submit_as_draft: true

